on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-build-${{ hashFiles('.ci_support/requirements-build.txt') }}
        restore-keys: |
          pip-build-
          pip-

    - run: |
        pip install -U -r .ci_support/requirements-build.txt

    - run: |
        jupyter-book build .

    - uses: actions/upload-artifact@v2
      with:
        name: _build
        path: _build

  spelling:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _build
          path: _build

      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key: conda-spelling-${{ hashFiles('.ci_support/environment-spelling.yml') }}
          restore-keys: |
            conda-spelling-
            conda-

      - uses: goanpeca/setup-miniconda@v1.6.0
        with:
          activate-environment: spelling
          channel-priority: strict
          environment-file: .ci_support/environment-spelling.yml
          use-only-tar-bz2: true

      - shell: bash -l {0}
        run: |
          bash .ci_support/check_spelling.sh

  links:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _build
          path: _build

      - uses: actions/cache@v2
        with:
          path: .pytest-check-links-cache.sqlite
          key: link-cache

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-check-links-${{ hashFiles('.ci_support/requirements-check-links.txt') }}
          restore-keys: |
            pip-check-links-
            pip-

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: |
          pip install -U -r .ci_support/requirements-check-links.txt

      - run: |
          bash .ci_support/check_links.sh
